/// Flutter icons ElLoboIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ElLoboIcons
///      fonts:
///       - asset: fonts/ElLoboIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ElLoboIcons {
  ElLoboIcons._();

  static const _kFontFam = 'ElLoboIcons';
  static const String? _kFontPkg = null;

  static const IconData joker = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cupid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData girl = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wolf = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData potion = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seer = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData protector = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hunter = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oldman = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData witch = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData villager = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child_wolf = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fool = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const List<IconData> icons = [villager, wolf, seer, cupid, witch, hunter, protector, oldman, girl, joker, fool, child_wolf, potion];
}
